# 2.1 Data Manipulation

2.1.1 Getting Started

In [1]:
from mxnet import np, npx

npx.set_np()

In [6]:
x = np.arange(12)
print(x)
print(x.shape)
print(x.size)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
(12,)
12


In [10]:
X = x.reshape(3, 4)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
np.random.normal(0, 1, size = (3, 4))

array([[ 1.1630787 ,  2.2122064 ,  0.4838046 ,  0.7740038 ],
       [ 0.29956347,  1.0434403 ,  0.15302546,  1.1839255 ],
       [-1.1688148 ,  1.8917114 ,  1.5580711 , -1.2347414 ]])

In [14]:
np.array( [[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]] )

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

2.1.2 Operations